function [] = plot_mcmc_posteriors_separate()

    %%% command:
    %%% plot_mcmc_posteriors_separate()
   
    clc;
    close all
    set(0,'DefaultFigureVisible','on');

    if ~exist('./figures', 'dir')
        mkdir('./figures')
    end

    chains_cyp2c9 = [];
    for ii = 1:5
        iichains = load(strcat('./MC2_fixed_cyp2c9_transcription/chains/chains_',num2str(ii),'.mat'));
        chains_cyp2c9 = [chains_cyp2c9; iichains.chains(:,:)];
    end
    
    chains_rif = [];
    for ii = 1:5
        iichains = load(strcat('./rifampicin/chains/chains_',num2str(ii),'.mat'));
        chains_rif = [chains_rif; iichains.chains(:,:)];
    end

    %%% Aggregated posterior plots %%%
    fontsize = 14;
    fontsize_pars = 16;
    leg = {{'RIF',...
           '25-DRIF'};...           
           {'RIF',...
           '25-DRIF'};...           
           {'RIF',...
           '25-DRIF'}};
    
    fcolor_rif  = {[0.75 0.75 0.75],[1 0 1],[0 1 1]};
    fcolor_drif = {[0 0 0],[1 0 0],[0 0 1]};
    vec         = [1,4,8];
    figlabs     = {'(A)',...
                   '(B)',...
                   '(C)'};
    params      = {'$k_\mathrm{pxr,max}$',...
                   '$k_{{mRNA}^\mathrm{fold}_\mathrm{cyp3a4}}$',...
                   '$k_{{mRNA}^\mathrm{fold}_\mathrm{cyp2b6}}$'};
    xaxis = {0.235;0.285;0.285};
    yaxis = {0.91;0.897;0.893};

    XLims = {[-2.5 0.0];...
             [-1.3 -0.8];...
             [-1.8 -0.6]};
    XTick = {-2.5:0.5:0.0;...
             -1.3:0.1:-0.8;...
             -1.8:0.2:0.6};

    figure();
    clc;
    tiledplot = tiledlayout(1,length(leg));
    set(gcf, 'Position',  [500, 300, 1200, 350]);
    clc;
    mm = 0;
    for aa = 1:length(leg)
        mm = mm+1;
        ax(mm) = nexttile(mm);
        set(ax(mm),...
            'box','on',...
            'XLim', XLims{mm},...
            'XTick',XTick{mm},...
            'YLim',[0 0.09],...
            'YTick',0:0.03:0.09,...
            'FontSize',fontsize);
        hold on;
        set(gca,'TickLength',[0.025, 0.025])
        histogram(log10(chains_rif(:,vec(mm))),50,...
              'FaceColor', 'none',...
              'EdgeColor', fcolor_rif{mm},...
              'FaceAlpha', 1,...
              'EdgeAlpha', 1,...
              'Normalization', 'probability',...
              'DisplayStyle', 'stairs',...
              'LineWidth',2);
        hold on;
        histogram(log10(chains_cyp2c9(:,mm)),50,...
              'FaceColor', 'none',...
              'EdgeColor', fcolor_drif{mm},...
              'FaceAlpha', 1,...
              'EdgeAlpha', 1,...
              'Normalization', 'probability',...
              'DisplayStyle', 'stairs',...
              'LineWidth',2);
        hold on;
        xlabel(ax(mm),'Log_{10} value','FontSize',fontsize);
        text(0.075,0.925,figlabs{mm},...
        'Units','Normalized',...
        'HorizontalAlignment','center',...
        'FontSize',fontsize,...
        'FontWeight','Normal'); 
        text(xaxis{mm},yaxis{mm},params{mm},...
        'Units','Normalized',...
        'HorizontalAlignment','center',...
        'FontSize',fontsize_pars,...
        'FontWeight','Normal', ...
        'interpreter','latex'); 
        l=legend(leg{mm});
        set(l,'Location','NorthOutside');
        set(l,'Orientation','Horizontal');
        set(l,'FontSize',fontsize);
    end    
    tiledplot.TileSpacing = 'compact';
    tiledplot.Padding = 'compact';

    savefig(strcat('figures/posteriors_rif_drif_comparison_separate.fig'));
    exportgraphics(gcf,'figures/posteriors_rif_drif_comparison_separate.png');
    exportgraphics(gcf,'./figures/posteriors_rif_drif_comparison_separate.eps','ContentType','vector');

end